"""Generate requirements.txt from pyproject.toml — the single source of truth.

§十八-3: requirements.txt and pyproject.toml used to be maintained in
parallel and drifted. This regenerates requirements.txt by flattening
``[project].dependencies`` plus every ``[project.optional-dependencies]``
group, so the checked-in requirements file can never silently diverge.

The torch line keeps its CUDA index-url guidance comment (torch must come
from the PyTorch wheel index on this machine, not PyPI).

Usage:
  PYTHONPATH=. ./.venv/Scripts/python scripts/maintenance/current/gen_requirements.py
"""
import tomllib

from stoke_ml.config import get_project_root

ROOT = get_project_root()
PYPROJECT = ROOT / "pyproject.toml"
REQUIREMENTS = ROOT / "requirements.txt"

BANNER = """\
# AUTO-GENERATED by scripts/maintenance/current/gen_requirements.py — DO NOT EDIT.
# pyproject.toml is the single source of truth for dependencies. Re-run the
# generator after any pyproject dependency change:
#   PYTHONPATH=. ./.venv/Scripts/python scripts/maintenance/current/gen_requirements.py
"""

TORCH_NOTE = (
    "# PyTorch with CUDA: install separately:\n"
    "#   pip install torch --index-url https://download.pytorch.org/whl/cu128\n"
)


def render(data: dict) -> str:
    """Flatten pyproject project/optional-dependencies into requirements text."""
    project = data.get("project", {})
    lines = [BANNER.rstrip(), ""]

    core = project.get("dependencies", [])
    if core:
        lines.append("# Core")
        lines.extend(core)
        lines.append("")

    extras = project.get("optional-dependencies", {})
    # Stable group order (pyproject insertion order is preserved by tomllib).
    for name, deps in extras.items():
        lines.append(f"# [{name}]")
        for dep in deps:
            if dep.startswith("torch="):
                lines.append(TORCH_NOTE.rstrip())
            lines.append(dep)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    data = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    text = render(data)
    REQUIREMENTS.write_text(text, encoding="utf-8")
    n = sum(1 for line in text.splitlines() if line and not line.startswith("#"))
    print(f"wrote {REQUIREMENTS} ({n} deps from pyproject.toml)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
